# install packages by Homebrew.
# $ brew tap Homebrew/brewdler
# $ brew bundle

tap 'atton/customs'
tap 'songmu/tap'

brew 'atton/customs/tmux'
brew 'awscli'
brew 'binutils'
brew 'cocoapods'
brew 'coreutils'
brew 'direnv'
brew 'exiftool'
brew 'findutils'
brew 'git'
brew 'gnu-sed'
brew 'go'
brew 'grep'
brew 'hub'
brew 'jq'
brew 'mercurial'
brew 'neovim'
brew 'nkf'
brew 'nmap'
brew 'nodenv'
brew 'nyancat'
brew 'peep'
brew 'python3'
brew 'q'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'rsync'
brew 'ssh-copy-id'
brew 'terminal-notifier'
brew 'unar'
brew 'w3m'
brew 'wget'
brew 'wine'
brew 'zsh'
