# install packages by Homebrew.
# $ brew tap Homebrew/brewdler
# $ brew bundle

# taps
tap 'atton/customs'
tap 'caskroom/homebrew-cask'
tap 'homebrew/binary'
tap 'homebrew/dupes'
tap 'neovim/neovim'
tap 'songmu/tap'

# formulae
brew 'atton/customs/tmux'
brew 'binutils'
brew 'coreutils'
brew 'direnv'
brew 'exiftool'
brew 'findutils'
brew 'ghc'
brew 'git'
brew 'gnu-sed'
brew 'go'
brew 'grep'
brew 'hub'
brew 'lua'
brew 'mercurial'
brew 'neovim'
brew 'nkf'
brew 'nmap'
brew 'nyancat'
brew 'pandoc'
brew 'peco'
brew 'peep'
brew 'python3'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'rsync'
brew 'ruby-build'
brew 'ssh-copy-id'
brew 'tree'
brew 'unar'
brew 'w3m'
brew 'wget'
brew 'yarn'
brew 'zsh'
