#!/bin/sh

branch="$(git symbolic-ref HEAD 2>/dev/null)" || \
       "$(git describe --contains --all HEAD)"

if [ "${branch##refs/heads/}" = "current" ]; then
    echo "+-------------------------------------+"
    echo "|'current' is my local working branch.|"
    echo "|Abort push action.                   |"
    echo "+-------------------------------------+"
    exit 1
fi
