#!/bin/sh

# busybox xargs not support -L option
if which busybox >& /dev/null; then exit 0; fi

FORBIDDEN='(<<<<<<<|>>>>>>>)'
GREP_COLOR='4;5;37;41'
cd $PWD

if [ -z "$(git diff --cached --diff-filter=ACMRTUXB)" ]; then
    exit 0
fi

git diff --cached --name-only --diff-filter=ACMRTUXB | xargs -L1 grep --color --with-filename -n -E $FORBIDDEN
if [[ $? -eq 0 ]]; then
    echo "Merge lines detected.\nPlease fix files, or run 'git commit --no-verify' to skip check."
    exit 1
fi
